"""
Reviewer Agent
--------------
Third and final link in the chain. This agent is the "quality and safety
gatekeeper": every post must pass through it before being marked ready
to publish.

Two kinds of checks happen together:
1. Deterministic checks via tools/content_safety_tool.py: text length and
   risky claims -- these are never left to the language model's subjective
   judgment, since they must always be precise and predictable.
2. Qualitative judgment from the language model: does the tone match the
   brand, is the content actually consistent with the original brief,
   does the phrasing read naturally.

This is exactly the course's "Security features" concept: an explicit
guardrail layer before the system's final output.
"""

from google.adk.agents import LlmAgent

import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import config
from agents.schemas import ReviewerOutput
from tools.content_safety_tool import check_post_length, check_risky_claims


def build_reviewer_agent() -> LlmAgent:
    """Builds the Reviewer Agent, wired up with the deterministic safety tools."""

    instruction = f"""
You are the content quality and safety reviewer for {config.BRAND_NAME}.

The posts generated by the writer are below:
{{writer_output}}

For each post, follow these steps exactly:

1. Call the check_post_length tool with that post's platform and text.
2. Call the check_risky_claims tool with that post's text.
3. If either tool returns any issues, record them in issues_found and set
   approved to false.
4. Beyond the tool results, also apply your own judgment:
   - Does the tone match the brand ({config.BRAND_TONE})?
   - Is the content genuinely faithful to the original brief's key_message?
   Add any problems you find here to issues_found as well.
5. If any issue was found, fix the text yourself and put the corrected
   version in final_text. If there was no issue, put the original text
   in final_text unchanged.

Return output strictly following the specified structure (ReviewerOutput)
for every post. Keep all post text in English.
"""

    return LlmAgent(
        name="reviewer_agent",
        model=config.GEMINI_MODEL,
        description="Runs security and quality checks on posts before final publish approval",
        instruction=instruction,
        tools=[check_post_length, check_risky_claims],
        output_schema=ReviewerOutput,
        output_key="reviewer_output",
    )


if __name__ == "__main__":
    agent = build_reviewer_agent()
    print(f"✅ Reviewer Agent built: {agent.name}")
    print(f"   Model: {agent.model}")
    print(f"   Tools attached: {len(agent.tools)}")
    print(f"   Expected output: {agent.output_schema.__name__}")
